### ISSUE TITLE
DRY-RUN in config

### ISSUE THREAD

**Issue by harb70** [monstermuffin/scripts#1]
Hi and thanks for this, very usefull.
I noticed something with the config file.
I had to comment the line DRY_RUN=false as in the backup script ${DRY_RUN:+--dry-run}  test if variable is present and not the value (true/false)

**Comment by monstermuffin** [comment]
Hey @harb70 

Thanks for the issue request. I had fixed this in an updated version that I had yet to commit to Github. I have done so now. Commit ca25e356c29f13819f6542e2ddf081e6d2f8fd19 has these fixes and brings the script up to date with my local version.

The fix for the dry run option specifically is to ensure that the `--dry-run` flag is set only when `DRY_RUN` is explicitly set to true in the configuration file.

```bash
[ "$DRY_RUN" = true ] && DRY_RUN_FLAG="--dry-run"
```

There were various other changes made which I have been using which seem to be fine in my setup. Can you repull the script and let me know if your issue is fixed or there are others? 

Thanks!

**Comment by harb70** [comment]
works like a charm !
